### ISSUE TITLE
Error while installing discovery-cli.

### ISSUE THREAD

**Issue by ycfung** [enigmampc/discovery-cli#23]
I'm exactly using the command ```npm install -g @enigmampc/discovery-cli``` to install it.
Here's some of the output:
```
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/lang.js'
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/fp/last.js'
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/last.js'
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/fp/lastIndexOf.js'
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/lastIndexOf.js'
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/fp/lastIndexOfFrom.js'
npm WARN tar ENOENT: no such file or directory, open '/root/.nvm/versions/node/v11.15.0/lib/node_modules/.staging/lodash-47f770d0/lodash.js'
npm WARN @truffle/decoder@3.0.15 requires a peer of truffle@^5.0.14 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! 
npm ERR! fatal: cannot come back to cwd: Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-07T13_03_06_844Z-debug.log

```
Actually there are tens of rows indicating the "no such file or directory" error. Even adding the parameters ```--unsafe-perm``` or```--allow-root``` doesn't work.
I'm using node v11.15 with nvm and npm v6.13.0 on Ubuntu 18.04. And i also have tried node v8 LTS and v10 LTS.

**Comment by lacabra** [comment]
Hi @ycfung, we have seen some permissions errors like the one you report above with the default installation of Node in some systems, where it has troubles installing global packages. Rather than reverting to `sudo` (this will only create more troubles), we highly recommend using [nvm](https://github.com/nvm-sh/nvm) to manage your Node installs. With Node installed with nvm, the global package install will go smoothly

**Comment by ycfung** [comment]
Thank you so much or replying @lacabra , I'm currently using nvm like I metioned above. And I only have a single root user so that no ```sudo``` command was used. I was wondering if the CLI is not very compatible with Ubuntu 18.04 amd64. So what Linux distribution do you prefer to test on? Should I use the root user to install it?

**Comment by lacabra** [comment]
Ah! I believe that you need to be on Intel infrastructure, even when running on Simulation mode, though you'll encounter SGX error more down the pipeline. I'm still surprised that you get Node install errors, but then regardless, my advice is to use Intel architecture to avoid further errors down the line.
