### ISSUE TITLE
Discovery init should create a gitignore file

### ISSUE THREAD

**Issue by JesseAbram** [enigmampc/discovery-cli#26]
Food for thought, I think it would be nice to have a gitignore with node modules, build, target.

**Comment by lacabra** [comment]
Absolutely, this is straightforward! Thanks for the suggestion 🙏

**Comment by levackt** [comment]
Will take a stab at this and send a PR next week.

**Comment by levackt** [comment]
> Will take a stab at this and send a PR next week.

See https://github.com/enigmampc/discovery-cli/pull/28
