### ISSUE TITLE
.env file has machine specific pathway. 

### ISSUE THREAD

**Issue by JesseAbram** [enigmampc/discovery-cli#27]
`BUILD_CONTRACTS_PATH=/Users/jesseabramowitz/Desktop/moodles/eth_waterloo/build/enigma_contracts
` 

this makes it harder working in teams. If I init then push to github and my teammates pull it down, it should probably cause issues.

**Comment by lacabra** [comment]
Right. The approach that we use in other repos is to have an `.env.template` that has a generic path and have `.env` in `.gitignore`. When a user clones your repo, it's instructed to `cp .env.template .env` and modify the file accordingly to that host, for example this one:
https://github.com/enigmampc/discovery-docker-network

We believe this is a reasonable approach, so won't fix anything here, unless you have suggestions on how to handle this better.

**Comment by JesseAbram** [comment]
Oh ya that makes a lot of sense good flow, didn't understand the flow, then probably with the .gitignore file issue from before adding .env too. Cheers!
